### PR TITLE
Unit Tests not running because of naming convention.

### LINKED ISSUE #17: Unit Tests don't run locally or in CI
Because of the way the test file is named it's not actually running under appveyor and locally running a simple invoke-pester ./Tests/ is not identifying the file because it ends in .test.ps1 instead of .Tests.ps1

### PR DESCRIPTION
**Pull request by TraGicCode**
This renames the tests file so that unit tests actually run in appveyor and when you run Invoke-Pester locally without explicitly passing the name of the file.

I Also went ahead and fixed the PSSA rules and markdown linting issues.

Fixes #17 

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xpowershellexecutionpolicy/16)

### CODE REVIEW

**Comment by johlju** [comment]
@TraGicCode thanks for fixing the tests! :smile:  Just a few review comments.

---

Reviewed 4 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[README.md, line 13 at r1](https://beta.reviewable.io/reviews/powershell/xpowershellexecutionpolicy/16#-L9zlZFB50xdJxYHvBsa:-L9zlZFB50xdJxYHvBsb:by0qtfm) ([raw file](https://github.com/powershell/xpowershellexecutionpolicy/blob/15655c46100966c7ca718a1a155fff8602e0410c/README.md#L13)):*
> ```Markdown
> 
> [Build status](https://ci.appveyor.com/project/PowerShell/xPowerShellExecutionPolicy/branch/master)
> [codecov](https://codecov.io/gh/PowerShell/xPowerShellExecutionPolicy/branch/master)
> ```

To get badges working for codecov there is a bit more that is needed (updated appveyor.yml). I suggest Codecov support is added in a separate PR, and that we remove this row from this PR.

---

*[README.md, line 21 at r1](https://beta.reviewable.io/reviews/powershell/xpowershellexecutionpolicy/16#-L9zm-GB3hVg8pmRg4VZ:-L9zm-GB3hVg8pmRg4V_:blvst96) ([raw file](https://github.com/powershell/xpowershellexecutionpolicy/blob/15655c46100966c7ca718a1a155fff8602e0410c/README.md#L21)):*
> ```Markdown
> 
> [Build status](https://ci.appveyor.com/project/PowerShell/xPowerShellExecutionPolicy/branch/dev)
> [codecov](https://codecov.io/gh/PowerShell/xPowerShellExecutionPolicy/branch/dev)
> ```

Please see previous comment.

---

*[README.md, line 43 at r1](https://beta.reviewable.io/reviews/powershell/xpowershellexecutionpolicy/16#-L9zosHU38MWBUtpHPZI:-L9zosHU38MWBUtpHPZJ:b-676qrc) ([raw file](https://github.com/powershell/xpowershellexecutionpolicy/blob/15655c46100966c7ca718a1a155fff8602e0410c/README.md#L43)):*
> ```
> [issue #1088]
> ```

We got  the wrong issue number here.

---

*[Tests/Unit/MSFT_xPowerShellExecutionpolicy.test.ps1, line 118 at r1](https://beta.reviewable.io/reviews/powershell/xpowershellexecutionpolicy/16#-L9znHg67FznUQvneo8W:-L9znHg67FznUQvneo8X:b-1avfzm) ([raw file](https://github.com/powershell/xpowershellexecutionpolicy/blob/b18bd90cd98ef655604354cfee9e9daaebb38611/Tests/Unit/MSFT_xPowerShellExecutionpolicy.test.ps1#L118)):*
> ```PowerShell
>             }
> 
>             It 'Throws when passed an invalid execution policy' {
> ```

Was test remove for a specific reason? It seemed to test the  `Scope` parameter. Maybe the It-block description should have been updated.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/xpowershellexecutionpolicy/16#-:-L9znzR2AEzioHYVmqVw:bslsftf)*

**Comment by TraGicCode** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[README.md, line 13 at r1](https://beta.reviewable.io/reviews/powershell/xpowershellexecutionpolicy/16#-L9zlZFB50xdJxYHvBsa:-LA0YxYqD8SENA5HgG5I:b-896fix) ([raw file](https://github.com/powershell/xpowershellexecutionpolicy/blob/15655c46100966c7ca718a1a155fff8602e0410c/README.md#L13)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

To get badges working for codecov there is a bit more that is needed (updated appveyor.yml). I suggest Codecov support is added in a separate PR, and that we remove this row from this PR.
</blockquote></details>

Done.

---

*[README.md, line 21 at r1](https://beta.reviewable.io/reviews/powershell/xpowershellexecutionpolicy/16#-L9zm-GB3hVg8pmRg4VZ:-LA0Yy7-CKh9RCAQyqKH:b-896fix) ([raw file](https://github.com/powershell/xpowershellexecutionpolicy/blob/15655c46100966c7ca718a1a155fff8602e0410c/README.md#L21)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Please see previous comment.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/xpowershellexecutionpolicy/16)*

**Comment by TraGicCode** [comment]
Review status: 2 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[README.md, line 43 at r1](https://beta.reviewable.io/reviews/powershell/xpowershellexecutionpolicy/16#-L9zosHU38MWBUtpHPZI:-LA0ZH-OD3h0_6E3T-ER:b-896fix) ([raw file](https://github.com/powershell/xpowershellexecutionpolicy/blob/15655c46100966c7ca718a1a155fff8602e0410c/README.md#L43)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> [issue #1088]
> ```

We got  the wrong issue number here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/xpowershellexecutionpolicy/16)*

**Comment by TraGicCode** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[Tests/Unit/MSFT_xPowerShellExecutionpolicy.test.ps1, line 118 at r1](https://beta.reviewable.io/reviews/powershell/xpowershellexecutionpolicy/16#-L9znHg67FznUQvneo8W:-LA0_uAi5KGpgJiIebab:b2yc0u2) ([raw file](https://github.com/powershell/xpowershellexecutionpolicy/blob/b18bd90cd98ef655604354cfee9e9daaebb38611/Tests/Unit/MSFT_xPowerShellExecutionpolicy.test.ps1#L118)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Was test remove for a specific reason? It seemed to test the  `Scope` parameter. Maybe the It-block description should have been updated.
</blockquote></details>

I actually got confused with the name.  I thought it was a duplicate test.  I added the test back and fixed the test name to make it correct.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/xpowershellexecutionpolicy/16)*

**Comment by TraGicCode** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[Tests/Unit/MSFT_xPowerShellExecutionpolicy.test.ps1, line 118 at r1](https://beta.reviewable.io/reviews/powershell/xpowershellexecutionpolicy/16#-L9znHg67FznUQvneo8W:-LA0a0ke2SSxfnCgqLKJ:b-896fix) ([raw file](https://github.com/powershell/xpowershellexecutionpolicy/blob/b18bd90cd98ef655604354cfee9e9daaebb38611/Tests/Unit/MSFT_xPowerShellExecutionpolicy.test.ps1#L118)):*
<details><summary><i>Previously, TraGicCode (Michael Fyffe) wrote…</i></summary><blockquote>

I actually got confused with the name.  I thought it was a duplicate test.  I added the test back and fixed the test name to make it correct.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/xpowershellexecutionpolicy/16)*

**Comment by johlju** [comment]
:lgtm:

@kwirkykat @mbreakey3 could you look at this and merge whenever you can? This makes the tests run correctly in AppVeyor.

---

Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/xpowershellexecutionpolicy/16#-:-LA3h2g329sey3DhxQBa:b-lkv9mo)*

**Pull request merged**
