### PR TITLE
Added codecov support

### LINKED ISSUE #18: Enable CodeCov Support
Hey @johlju ,

What is the process i need to follow in order to enable codecov for this?

### PR DESCRIPTION
**Pull request by TraGicCode**
This enabled code coverage.

Fixes #18 

This change is [Reviewable](https://reviewable.io/reviews/powershell/xpowershellexecutionpolicy/19)

### CODE REVIEW

**Comment by TraGicCode** [comment]
@johlju What needs to be done to fix the pip install error at the bottom of appveyor?

**Comment by johlju** [comment]
Hmm... That seems yet as a new problem, the last error you get we started seeing a while back, see issue https://github.com/PowerShell/DscResource.Tests/issues/203.
It doesn't affect uploading to Codecov (yet), see the file codeCovUpload.log here https://ci.appveyor.com/project/PowerShell/xpowershellexecutionpolicy/build/1.0.66.0/artifacts, it uploads successfully.

Since the problem are escalating we should move to the alternate method mentioned in one of the last comments the above issue in the DscResource.Tests repo.

**Comment by johlju** [comment]
@TraGicCode Please rebase this PR and resolve the merge conflicts. Please use `git rebase` (and not `git pull` or `git merge`). 😃

**Comment by johlju** [comment]
@TraGicCode Remember to add the Codecov badges, looked like they warn't part of the PR? 😃

**Comment by TraGicCode** [comment]
Hey @johlju,

I rebased to fix the merge conflict along with adding the codecov badges to the readme.  In regards to the python issue i'm not following what alternate method we should use for this.

---







*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/xpowershellexecutionpolicy/19#-:-LAaGNkU45A8kBdC_g3P:blhufb4)*

**Comment by johlju** [comment]
@TraGicCode Ah, sorry, it was just thinking loud that we (as in the community), in the DscResource.Tests repo, should move the test framework to use an alternate method to uploading the Codecov file. You don't have to do anything in this PR. :) We ignore the errors for now.

I will review this one in a bit. 😃

**Comment by johlju** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[appveyor.yml, line 1 at r2](https://beta.reviewable.io/reviews/powershell/xpowershellexecutionpolicy/19#-LAax1CY7pPv4iPdLDfQ:-LAax1CY7pPv4iPdLDfR:bgbx8rf) ([raw file](https://github.com/powershell/xpowershellexecutionpolicy/blob/a6a84297da7047f9930e5b56f7e750b21d0ad3e6/appveyor.yml#L1)):*
> ```YAML
> ################################################################################
> ```

Please remove this comment block (line 1-9)

---

*[appveyor.yml, line 15 at r2](https://beta.reviewable.io/reviews/powershell/xpowershellexecutionpolicy/19#-LAawp5TB7H2j-hV0f7p:-LAawp5TB7H2j-hV0f7q:b-48o6nc) ([raw file](https://github.com/powershell/xpowershellexecutionpolicy/blob/a6a84297da7047f9930e5b56f7e750b21d0ad3e6/appveyor.yml#L15)):*
> ```
> 1.0.{build}
> ```

Please change this to `1.1.{build}.0` which is the version in the file in the dev branch.
Please remove the 'TODO:' comment.

---

*[appveyor.yml, line 34 at r2](https://beta.reviewable.io/reviews/powershell/xpowershellexecutionpolicy/19#-LAaxJMc1HiuTZ8j_QSS:-LAaxJMc1HiuTZ8j_QST:blp4vrs) ([raw file](https://github.com/powershell/xpowershellexecutionpolicy/blob/a6a84297da7047f9930e5b56f7e750b21d0ad3e6/appveyor.yml#L34)):*
> ```YAML
> test_script:
>     - ps: |
>         # TODO:
> ```

Please remove the TODO: comment block (line 34-36)

---

*[README.md, line 21 at r2](https://beta.reviewable.io/reviews/powershell/xpowershellexecutionpolicy/19#-LAaxj-a3hKM5-OmpqN7:-LAaxj-a3hKM5-OmpqN8:b-qyifm1) ([raw file](https://github.com/powershell/xpowershellexecutionpolicy/blob/a6a84297da7047f9930e5b56f7e750b21d0ad3e6/README.md#L21)):*
> ```
> branch/master
> ```

We should set this to 'branch/dev' (at two locations in this line)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/xpowershellexecutionpolicy/19)*

**Comment by TraGicCode** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[appveyor.yml, line 1 at r2](https://beta.reviewable.io/reviews/powershell/xpowershellexecutionpolicy/19#-LAax1CY7pPv4iPdLDfQ:-LAdNMav2n7aj7gu7cC6:b-896fix) ([raw file](https://github.com/powershell/xpowershellexecutionpolicy/blob/a6a84297da7047f9930e5b56f7e750b21d0ad3e6/appveyor.yml#L1)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Please remove this comment block (line 1-9)
</blockquote></details>

Done.

---

*[appveyor.yml, line 15 at r2](https://beta.reviewable.io/reviews/powershell/xpowershellexecutionpolicy/19#-LAawp5TB7H2j-hV0f7p:-LAdNM0s-2RdoxcaQDjX:b-896fix) ([raw file](https://github.com/powershell/xpowershellexecutionpolicy/blob/a6a84297da7047f9930e5b56f7e750b21d0ad3e6/appveyor.yml#L15)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> 1.0.{build}
> ```

Please change this to `1.1.{build}.0` which is the version in the file in the dev branch.
Please remove the 'TODO:' comment.
</blockquote></details>

Done.

---

*[appveyor.yml, line 34 at r2](https://beta.reviewable.io/reviews/powershell/xpowershellexecutionpolicy/19#-LAaxJMc1HiuTZ8j_QSS:-LAdNMowCAGyMHLsf6J3:b-896fix) ([raw file](https://github.com/powershell/xpowershellexecutionpolicy/blob/a6a84297da7047f9930e5b56f7e750b21d0ad3e6/appveyor.yml#L34)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Please remove the TODO: comment block (line 34-36)
</blockquote></details>

Done.

---

*[README.md, line 21 at r2](https://beta.reviewable.io/reviews/powershell/xpowershellexecutionpolicy/19#-LAaxj-a3hKM5-OmpqN7:-LAdNIbz10jP71KSCGqC:b-896fix) ([raw file](https://github.com/powershell/xpowershellexecutionpolicy/blob/a6a84297da7047f9930e5b56f7e750b21d0ad3e6/README.md#L21)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> branch/master
> ```

We should set this to 'branch/dev' (at two locations in this line)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/xpowershellexecutionpolicy/19)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/xpowershellexecutionpolicy/19#-:-LAdTnj_D5lW0pCZA7sK:bnfp4nl)*

**Pull request merged**
